name: Deploy Azure Infrastructure

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.12.2

      - name: Terraform Init (Backend disabled for validation)
        run: terraform init -backend=false

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Format Check
        run: terraform fmt -check
        continue-on-error: true

  deploy:
    runs-on: ubuntu-latest
    needs: validate
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    environment: production
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.12.2

      - name: Manual Deployment Notice
        run: |
          echo "🚨 MANUAL DEPLOYMENT REQUIRED"
          echo "Due to student account limitations, please deploy manually:"
          echo "1. Ensure you're logged in: az login"
          echo "2. Run: terraform init"
          echo "3. Run: terraform plan"
          echo "4. Run: terraform apply"
          echo ""
          echo "✅ Code validation passed - ready for manual deployment!"
