name: Terraform Infra Apply

on:
  push:
    branches: [main]

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Terraform Init & Apply
        run: |
          terraform init
          terraform apply -auto-approve
          terraform output -json > tf-outputs.json

      - name: Upload Terraform Output Artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-outputs
          path: tf-outputs.json

