name: Deploy App from Infra Artifact

on:
  workflow_dispatch:
jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.12.2  # Optional: pin the version

      - name: Terraform Init & Apply
        run: |
          terraform init
          terraform apply -auto-approve
          terraform output -json > tf-outputs.json

      - name: Upload Terraform Outputs
        uses: actions/upload-artifact@v4
        with:
          name: terraform-outputs
          path: tf-outputs.json
